In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.1.0'

In [5]:
dataset = pd.read_csv('C:/Users/indra/Documents/Udemy/Deep Learning/ANN/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [9]:
print(y)

[1 0 1 ... 1 1 0]


In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [12]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
ann = tf.keras.models.Sequential()

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [21]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [22]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 2s 255us/sample - loss: 0.5255 - accuracy: 0.7949
Epoch 2/100
8000/8000 [==============================] - 0s 28us/sample - loss: 0.4610 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4404 - accuracy: 0.7966
Epoch 4/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.4331 - accuracy: 0.8010
Epoch 5/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4300 - accuracy: 0.8031
Epoch 6/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4278 - accuracy: 0.8054
Epoch 7/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4261 - accuracy: 0.8054
Epoch 8/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4246 - accuracy: 0.8070
Epoch 9/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4233 - accuracy: 0.8100
Epoch 10/100
8000/8000 

Epoch 77/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4001 - accuracy: 0.8344
Epoch 78/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.3999 - accuracy: 0.8356
Epoch 79/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.3997 - accuracy: 0.8338
Epoch 80/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.3996 - accuracy: 0.8349
Epoch 81/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.3991 - accuracy: 0.8340
Epoch 82/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3992 - accuracy: 0.8354
Epoch 83/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.3992 - accuracy: 0.8346
Epoch 84/100
8000/8000 [==============================] - 0s 28us/sample - loss: 0.3993 - accuracy: 0.8335
Epoch 85/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.3990 - accuracy: 0.8345
Epoch 86/100
8000/8000 [=============

In [23]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1533   62]
 [ 256  149]]


0.841